In [13]:
import pandas
import pickle
import os

In [15]:
with open('./features.pkl', 'rb') as fid:        
    d = pickle.load(fid)
data = pandas.DataFrame(d)
data.describe()

,area,below,horizon_inclination,left,right,up,vertical_inclination
count,2019.000000,2019.000000,2019.000000,2019.000000,2019.000000,2019.000000,2019.000000
mean,4728.483408,95.241134,0.180584,32.871294,32.851192,95.329295,0.127093
std,14497.713299,124.732650,0.583233,40.370454,40.232012,124.561943,0.267197
min,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,208.500000,17.029386,0.050000,9.055385,9.219544,17.189960,0.000000
50%,945.000000,50.249378,0.100000,19.646883,20.000000,51.000000,0.050000
75%,4267.500000,124.074554,0.200000,41.060901,41.000000,123.389064,0.150000
max,395791.000000,1529.162189,20.000000,607.161428,608.066608,1523.434606,6.450000